FLASK_APP=main.py
PORT=5000
FLASK_ENV=development
MONGODB_URL=localhost
MQTT_HOST=test.mosquitto.org
MQTT_PORT=1883
MQTT_USE_SSL=False

MAIL_SERVER=localhost
MAIL_PORT=8025
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_USE_TLS=0
MAIL_USE_SSL=0