FLASK_APP=main.py
FLASK_ENV=development
MONGODB_URL=mongodb://localhost:27017/zelite_dev
MQTT_HOST=127.0.0.1
MQTT_PORT=1883
MQTT_USE_SSL=0

SEND_EMAIL=0
MAIL_SERVER=localhost
MAIL_PORT=8025
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_USE_TLS=0
MAIL_USE_SSL=0